README.md, core/iwasm/products/linux/CMakeLists.txt, core/iwasm/products/linux/main.c, core/iwasm/runtime/vmcore-wasm/wasm_interp.c, core/iwasm/runtime/vmcore-wasm/wasm_loader.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.h, core/shared-lib/include/bh_memory.h, core/shared-lib/include/config.h, core/shared-lib/mem-alloc/bh_memory.c, core/shared-lib/platform/linux/bh_thread.c
* Implement memory profiler, optimize memory usage, modify code indent
* Implement memory.grow and limit heap space base offset to 1G; modify iwasm build type to Release and 64 bit by default
=> Implement memory.grow and limit heap space base offset to 1G (#36)

README.md, core/iwasm/products/vxworks/CMakeLists.txt, core/iwasm/products/vxworks/ext_lib_export.c, core/iwasm/products/vxworks/main.c, core/iwasm/runtime/platform/vxworks/platform.cmake, core/iwasm/runtime/platform/vxworks/wasm_native.c, core/iwasm/runtime/platform/vxworks/wasm_platform.c, core/iwasm/runtime/platform/vxworks/wasm_platform.h, core/shared-lib/platform/vxworks/bh_assert.c, core/shared-lib/platform/vxworks/bh_definition.c, core/shared-lib/platform/vxworks/bh_platform.c, core/shared-lib/platform/vxworks/bh_platform.h, core/shared-lib/platform/vxworks/bh_platform_log.c, core/shared-lib/platform/vxworks/bh_thread.c, core/shared-lib/platform/vxworks/bh_time.c, core/shared-lib/platform/vxworks/shared_platform.cmake
This adds iwasm support for VxWorks 7.
=> Add support for VxWorks (#43)

core/iwasm/lib/native/libc/libc_wrapper.c, core/iwasm/products/linux/main.c, core/iwasm/runtime/vmcore-wasm/wasm_interp.c, core/iwasm/runtime/vmcore-wasm/wasm_loader.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.c
* Implement memory profiler, optimize memory usage, modify code indent
* Implement memory.grow and limit heap space base offset to 1G; modify iwasm build type to Release and 64 bit by default
* Add a new extension library: connection
* Fix bug of reading magic number and version in big endian platform
* Re-org platform APIs: move most platform APIs from iwasm to shared-lib
* Enhance wasm loader to fix some security issues
=> Enhance wasm loader to fix some security issues (#91)

core/iwasm/runtime/vmcore-wasm/invokeNative_arm.s, core/iwasm/runtime/vmcore-wasm/invokeNative_general.c, core/iwasm/runtime/vmcore-wasm/invokeNative_mips.s, samples/gui/README.md
Re-implement them due to the function prototype was changed.
Fix typo of sample/gui/README.
=> Re-implement invokeNative function of arm/mips/general version (#125)

core/iwasm/interpreter/wasm_loader.c
Otherwise a block opcode with invalid type signature could crash the
wasm loader.
=> bugfix: check type for opcode block, loop and if (#238) (#239)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/compilation/aot.c, core/iwasm/compilation/aot.h, core/iwasm/compilation/aot_emit_function.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h, core/shared/platform/android/platform_internal.h, core/shared/platform/common/posix/posix_thread.c, core/shared/platform/darwin/platform_internal.h, core/shared/platform/linux/platform_internal.h, core/shared/platform/vxworks/platform_internal.h, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/iwasm_main.c
And separate global data from wasm memory instance
=> Refine aot stack overflow check and enhance wasm loader malformed checks (#248)

core/shared/utils/bh_log.c, core/shared/utils/bh_log.h
* rename loglevel enums
* Update bh_log.c
=> Rename log_level enums (#252)

core/iwasm/include/wasm_export.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/shared/platform/common/posix/posix_thread.c
and fix issues of get native stack boundary
=> Update API comments, refine footprint of wasm loader (#256)

core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/compilation/aot_emit_control.c, core/iwasm/compilation/aot_emit_memory.c
fix aot 32-bit boundary check issue
=> Fix aot issue in 32-bit platform (#297)

core/app-mgr/app-manager/module_wasm_app.c
* fix comments wrong position
* fix one typo in module_wasm_app.c's log
=> fix one typo in module_wasm_app.c's log (#299)

README.md
Signed-off-by: yijin.syj <yijin.syj@antgroup.com>
Co-authored-by: yijin.syj <yijin.syj@alibaba-inc.com>
=> Fix one typo in README.md (#309)

core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_native.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_runtime_common.h, core/iwasm/include/wasm_export.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h, core/iwasm/libraries/libc-builtin/libc_builtin_wrapper.c, core/iwasm/libraries/libc-wasi/libc_wasi_wrapper.c, core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c, core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/random.c, core/shared/platform/common/posix/posix_memmap.c, core/shared/platform/common/posix/posix_thread.c, doc/embed_wamr.md, samples/basic/src/main.c, samples/littlevgl/vgl-wasm-runtime/src/platform/linux/display_indev.c
And fix some sign/unsigned conversion compilation warnings.
=> Change wasm app offset type from int32 to uint32 (#361)

README.md, core/shared/platform/nuttx/nuttx_platform.c, core/shared/platform/nuttx/nuttx_thread.c, core/shared/platform/nuttx/platform_internal.h, core/shared/platform/nuttx/shared_platform.cmake, doc/build_wamr.md, product-mini/platforms/nuttx/main.c, product-mini/platforms/nuttx/wamr.mk
=> Introduce support for NuttX RTOS (#377)

core/shared/platform/include/platform_common.h, core/shared/utils/bh_log.h
=> core/shared: Add guard to avoid redefine macro (#386)

core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/compilation/aot_emit_numberic.c, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_runtime.h, core/shared/platform/common/posix/posix_thread.c, wamr-compiler/CMakeLists.txt
Signed-off-by: Xiaokang Qin <xiaokang.qxk@antgroup.com>
=> Fix the build warnings on Mac (#388)

.github/workflows/mac.yml
* Update linux.yml
* Create mac.yml
=> add more build option and samples in CI (#394)

build-scripts/config_common.cmake, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, doc/build_wamr.md
Add the function name field for internal function struct
Signed-off-by: Zhongmin Wu <vwzm@live.com>
Signed-off-by: Xiaokang Qin <xiaokang.qxk@antgroup.com>
Co-authored-by: Zhongmin Wu <vwzm@live.com>
=> Add the support for custom name section (#398)

doc/linux_sgx.md, product-mini/platforms/linux-sgx/enclave-sample/App/README.md
This commit mainly simplifies the description about building a
debug and hw mode enclave.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>
Co-authored-by: root <root@rs1g04412.et2sqa>
=> Update SGX documents (#439)

core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h
Add more llvm optimization passes to improve AOT/JIT performance
=> Add more llvm optimization passes (#445)

product-mini/platforms/nuttx/wamr.mk
=> platform/NuttX: Add support for lib pthread (#463)

core/iwasm/libraries/lib-pthread/lib_pthread_wrapper.c, core/shared/platform/common/posix/posix_thread.c
1. pthread_join can't get return value from exited threads
2. pthread_cond_wait return success when timeout
=> fix pthread library issues: (#522)

product-mini/platforms/nuttx/wamr.mk
=> platforms/nuttx: Add FPU relative macro for thumb vfp (#541)

product-mini/platforms/nuttx/wamr.mk
Signed-off-by: Masayuki Ishikawa <Masayuki.Ishikawa@jp.sony.com>
=> product-mini/nuttx: Add support for ARMV7A (#643)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_runtime_common.c, core/shared/platform/windows/win_thread.c, samples/wasm-c-api/src/trap.c
=> Fix wasm-c-api trap message format issue (#644)

core/shared/platform/nuttx/platform_internal.h, product-mini/platforms/nuttx/wamr.mk
=> platform/nuttx: Support riscv based chips (#648)

.github/workflows/linux.yml, core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_c_api_internal.h, core/iwasm/common/wasm_runtime_common.h, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h, samples/wasm-c-api/CMakeLists.txt, samples/wasm-c-api/src/hello.c
And update CI workflow to build/cache llvm and run wasm-c-api samples.
=> Implement wasm-c-api frame/trap APIs for AOT mode (#663)

core/iwasm/aot/arch/aot_reloc_riscv.c
=> Support R_RISCV_LO12_I/S in AOT

core/iwasm/aot/arch/aot_reloc_riscv.c
=> Minor fix for code format and data type

.github/workflows/android.yml, .github/workflows/linux.yml, README.md, doc/build_wasm_app.md
Update CI rules to improve CI build speed, update document about arch support and update document of wamrc help.
=> Update documents (#669)

README.md
* Update README.md
* Update the TSC member
=> Update the readme.md for TSC member  (#681)

tests/wamr-test-suites/test_wamr.sh
Build several projects in wamr-test-suites with multiple cores to reduce
the compilation time.
=> Build projects in wamr-test-suites with multiple cores (#811)

core/iwasm/compilation/aot_emit_aot_file.c
Simplify some string size calculation when emitting AOT file
=> Simplify some string size calculation when emitting AOT file (#813)

.github/workflows/compilation_on_sgx.yml
Add CI tasks on SGX platform:
build iwasm with some feature combinations
build and run some samples
test spec cases with interpreter mode and AOT mode
=> Add CI tasks on SGX platform (#817)

core/iwasm/common/wasm_application.c, core/iwasm/compilation/aot_compiler.c
And fix read_leb byte count check issue in aot_compiler.c
=> Remove PRI macro control in wasm_application.c (#905)

core/iwasm/libraries/thread-mgr/thread_manager.c, core/iwasm/libraries/thread-mgr/thread_manager.h
And refine the code format of thread_manager.h
=> Fix pointer unchecked issue in thread-mgr.c (#960)

core/iwasm/fast-jit/cg/x86-64/jit_codegen_x86_64.cpp, core/iwasm/fast-jit/fe/jit_emit_control.c, core/iwasm/fast-jit/jit_codecache.c, core/iwasm/fast-jit/jit_codegen.c, core/iwasm/fast-jit/jit_compiler.c, core/iwasm/fast-jit/jit_compiler.h, core/iwasm/fast-jit/jit_dump.c, core/iwasm/fast-jit/jit_frontend.c, core/iwasm/fast-jit/jit_ir.def, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_loader.c, product-mini/platforms/linux/CMakeLists.txt
Implement part of codegen and fix some frontend issues
Add asmjit to emit native code and add zydis to disassemble native code
Can successfully run some simple cases
=> Implement part of codegen, add asmjit and zydis (#1050)

core/iwasm/common/gc/gc_object.c, core/iwasm/common/gc/gc_object.h, core/iwasm/common/wasm_application.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_runtime_common.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h
Implement interpreter module instantiation process for GC
Implement most GC opcodes for classic interpreter
Successfully pass most GC spec cases
=> Implement instantiation and classic interpreter for GC feature (#1025)

core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/libraries/debug-engine/gdbserver.c, core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c, core/shared/utils/bh_vector.c, samples/wasm-c-api/src/reflect.c, tests/benchmarks/jetstream/build.sh
Fix issues reported by klocwork, fix host_tool compile error,
and update build script of benchmark jetstream
=> Fix issues reported by klocwork (#1060)

core/iwasm/libraries/libc-builtin/libc_builtin_wrapper.c
The format specifiers of %ld/%lu/%li/%lx/%lp/%lo (or %z* and %t* like) should
be treated as 32-bit integer in wasm.
And merge the handle of unsigned/signed for %u/%d and %llu/%lld specifier
when calling snprintf.
=> Fix %ld specifier issue in libc-builtin printf wrapper (#1088)

core/iwasm/common/wasm_runtime_common.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, product-mini/platforms/zephyr/simple/build_and_run.sh
And update the Zephyr platform sample help, add arc target into usage list.
=> Fix Windows compilation warnings (#1171)

core/iwasm/interpreter/wasm_interp.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/shared/mem-alloc/ems/ems_gc.c, core/shared/mem-alloc/ems/ems_gc.h
Implement the GC opcodes and GC heap reclaim process for
fast interpreter.
=> Implement GC feature for fast interpreter (#1184)

core/iwasm/common/gc/gc_object.c, core/iwasm/common/gc/gc_object.h, core/iwasm/common/gc/gc_type.c, core/iwasm/common/gc/gc_type.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h
Implement GC opcode fund.bind for classic interp and fast interp
=> Implement GC opcode fund.bind (#1246)

core/iwasm/interpreter/wasm_runtime.c
When de-instantiating the wasm module instance, remove it from the module's instance list before freeing func_ptrs and fast_jit_func_ptrs of the instance, to avoid accessing these freed memory in the JIT backend compilation threads.
=> Fix jit memory overwritten after instance deinstantiate (#1936)

core/iwasm/libraries/lib-wasi-threads/test/update_shared_data_and_alloc_heap.c
In the WASI thread test modified in this PR, malloc was used in multiple threads without a lock. But wasi-libc implementation of malloc is not thread-safe.
=> Fix malloc non-thread-safe usage in lib-wasi-threads test (#2022)

core/iwasm/common/wasm_memory.c, core/iwasm/common/wasm_shared_memory.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_runtime.h, core/iwasm/libraries/thread-mgr/thread_manager.c
To add test cases and samples.
=> Refactor shared heap feature for interpreter mode (#3794)
