core/iwasm/lib/native-interface/wasm_export.h, core/iwasm/lib/native/base/base_lib_export.c, core/iwasm/products/alios-things/src/main.c, core/iwasm/products/linux/main.c, core/iwasm/products/vxworks/main.c, core/iwasm/products/zephyr/simple/src/main.c, core/iwasm/runtime/include/wasm_export.h, core/iwasm/runtime/vmcore-wasm/wasm_interp.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.h, core/shared-lib/include/config.h
Enable setting external memory space for wasm app, the feature is disabled by default;
Remove wasm_application_exectue_* APIs from wasm_export.h which makes confused.
=> Enable native/app address validation and conversion for wasm app (#102)

core/iwasm/lib/native/libc/libc_wrapper.c, core/iwasm/products/linux/CMakeLists.txt, core/iwasm/products/zephyr/simple/src/main.c, core/iwasm/runtime/include/bh_memory.h, core/iwasm/runtime/vmcore-wasm/wasm_application.c, core/iwasm/runtime/vmcore-wasm/wasm_interp.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.c
* Implement memory profiler, optimize memory usage, modify code indent
* Implement memory.grow and limit heap space base offset to 1G; modify iwasm build type to Release and 64 bit by default
* Add a new extension library: connection
* Fix bug of reading magic number and version in big endian platform
* Re-org platform APIs: move most platform APIs from iwasm to shared-lib
* Enhance wasm loader to fix some security issues
* Fix issue about illegal load of EXC_RETURN into PC on stm32 board
* Updates that let a restricted version of the interpreter run in SGX
* Enable native/app address validation and conversion for wasm app
* Remove wasm_application_exectue_* APIs from wasm_export.h which makes confused
* Refine binary size and fix several minor issues
Optimize interpreter LOAD/STORE …
=> Refine binary size and fix several minor issues (#104)

CODE_OF_CONDUCT.md, CONTRIBUTING.md
See https://01.org/blogs/2018/intel-covenant-code
=> Document the Contributor Covenant as our Code of Conduct. (#116)

core/iwasm/lib/native/extension/gui/wgl_btn_wrapper.c, core/iwasm/lib/native/extension/gui/wgl_cb_wrapper.c, core/iwasm/lib/native/extension/gui/wgl_label_wrapper.c, core/iwasm/lib/native/extension/gui/wgl_list_wrapper.c, core/iwasm/lib/native/extension/gui/wgl_native_utils.c, core/iwasm/lib/native/extension/gui/wgl_native_utils.h, core/iwasm/lib/native/extension/gui/wgl_obj_wrapper.c, core/iwasm/runtime/vmcore-wasm/wasm_interp.c, core/iwasm/runtime/vmcore-wasm/wasm_runtime.c
Refine wgl lib: remove module_inst parameter from widget functions
Refine wasm function check: move function index check from interpreter call_indirect to runtime instantiate
=> Refine wgl lib and refine wasm function index check (#122)

core/iwasm/lib/app-libs/base/wasm_app.h, core/iwasm/lib/native-interface/shared_utils.h, core/iwasm/runtime/vmcore-wasm/wasm_interp.c, core/shared-lib/include/config.h, samples/gui/wasm-apps/lvgl-compatible/Makefile, samples/gui/wasm-apps/wgl/Makefile, samples/gui/wasm-runtime-wgl/linux-build/CMakeLists.txt, samples/gui/wasm-runtime-wgl/zephyr-build/CMakeLists.txt, samples/simple/CMakeLists.txt, samples/simple/README.md, samples/simple/build_no_gui.sh, samples/simple/src/ext_lib_export.c, samples/simple/src/iwasm_main.c
* Implement memory profiler, optimize memory usage, modify code indent
* Implement memory.grow and limit heap space base offset to 1G; modify iwasm build type to Release and 64 bit by default
* Add a new extension library: connection
* Fix bug of reading magic number and version in big endian platform
* Re-org platform APIs: move most platform APIs from iwasm to shared-lib
* Enhance wasm loader to fix some security issues
* Fix issue about illegal load of EXC_RETURN into PC on stm32 board
* Updates that let a restricted version of the interpreter run in SGX
* Enable native/app address validation and conversion for wasm app
* Remove wasm_application_exectue_* APIs from wasm_export.h which makes confused
* Refine binary size and fix several minor issues
Optimize interpreter LOAD/STORE …
=> Add a switch to build simple sample without gui support (#126)

core/iwasm/aot/aot_loader.c, core/iwasm/interpreter/wasm_loader.c
Co-authored-by: Xu Jun <jun1.xu@intel.com>
=> fix aot load import global bug && enhance dead code processing (#203)

README.md, core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.h, core/iwasm/aot/arch/aot_reloc_xtensa.c, core/iwasm/compilation/aot_emit_aot_file.c, core/iwasm/compilation/aot_emit_numberic.c, core/iwasm/compilation/aot_llvm.c, core/shared/platform/zephyr/platform_internal.h, core/shared/platform/zephyr/zephyr_platform.c, doc/build_wamr.md, doc/build_wasm_app.md, product-mini/platforms/alios-things/aos.mk, product-mini/platforms/zephyr/simple/CMakeLists.txt, product-mini/platforms/zephyr/simple/build.sh, product-mini/platforms/zephyr/simple/esp32_custom_linker.ld, product-mini/platforms/zephyr/simple/prj_esp32.conf, product-mini/platforms/zephyr/simple/prj_qemu_xtensa.conf, product-mini/platforms/zephyr/simple/src/main.c, wamr-compiler/build_llvm_xtensa.sh, wamr-compiler/main.c
* Clean compiling warnings of zephyr samples
* Support xtensa AOT and fix build issue of alios
=> Add xtensa AOT support and fix build issue of alios (#223)

core/iwasm/compilation/aot_emit_aot_file.c
* add darwin support for wamr-compiler compiling
* add darwin support for wamr-compiler
* Update CMakeLists.txt
* MacOs: fix wamrc Error invaid llvm binary bin_type
Co-authored-by: wenyongh <wenyong.huang@intel.com>
=> MacOs: fix wamrc Error invaid llvm binary bin_type (#269)

core/app-mgr/app-manager/module_wasm_app.c, core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/compilation/aot.c, core/iwasm/compilation/aot.h, core/iwasm/compilation/aot_compiler.c, core/iwasm/compilation/aot_emit_aot_file.c, core/iwasm/compilation/aot_emit_memory.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h, core/shared/platform/common/posix/posix_memmap.c, core/shared/platform/darwin/platform_init.c, core/shared/platform/darwin/platform_internal.h, core/shared/platform/linux-sgx/sgx_platform.c, core/shared/platform/linux/platform_init.c, core/shared/platform/linux/platform_internal.h, core/shared/platform/vxworks/platform_init.c, core/shared/platform/vxworks/platform_internal.h, core/shared/utils/bh_log.h, samples/wasm-c-api/src/callback.c
Insert app heap before __heap_base, or before new page
Fix os_printf compilation error in some platforms
=> Refactor app heap and memory boundary check, and fix os_printf compilation error (#356)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/arch/aot_reloc_x86_64.c, core/iwasm/compilation/aot_emit_aot_file.c, core/shared/platform/windows/win_memmap.c
Add the Windows COFF format support to wamr-compiler and iwasm can
load and excute it on Windows(X64) platform.
Signed-off-by: Wu Zhongmin <vwzm@live.com>
Signed-off-by: Xiaokang Qin <xiaokang.qxk@antgroup.com>
Co-authored-by: Wu Zhongmin <vwzm@live.com>
=> Add the Windows COFF format support for AOT (#382)

core/config.h
=> Use macro instead of enum to define MEM_ALLOCATOR for better compatibility (#399)

core/iwasm/aot/aot_runtime.c, core/iwasm/interpreter/wasm_runtime.c
* Add NULL check for memory page in aot/wasm module malloc/free
* Update aot_runtime.c
* Update wasm_runtime.c
Co-authored-by: Wenyong Huang <wenyong.huang@intel.com>
=> Add NULL check for memory inst in aot/wasm module malloc/free (#403)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/interpreter/wasm_runtime.c, core/shared/mem-alloc/ems/ems_alloc.c, core/shared/mem-alloc/ems/ems_gc.h, core/shared/mem-alloc/ems/ems_gc_internal.h, core/shared/mem-alloc/ems/ems_hmu.c, core/shared/mem-alloc/ems/ems_kfc.c, core/shared/mem-alloc/mem_alloc.c, core/shared/mem-alloc/mem_alloc.h
1. move heap struct out of linear memory
2. add pointer address checks for hmu nodes
=> Add more checks for app heap

doc/linux_sgx.md, product-mini/platforms/linux-sgx/enclave-sample/App/README.md, product-mini/platforms/linux-sgx/enclave-sample/App/wamr-bundle.md
The global doc/linux_sgx.md needs to explicitly describe the methods to
build a debug enclave and hardware running mode. Because using debug key
to signing enclave image rather than production key is still not trivial
in reality.
For the adaption of Inclavare Containers part, add a prolog and give
more details in order to enhance the readability.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>
=> Enhance the readability of WAMR SGX docs (#442)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/arch/invokeNative_em64_simd.s, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_shared_memory.c, core/iwasm/compilation/aot_compiler.h, core/iwasm/compilation/aot_emit_aot_file.c, core/iwasm/compilation/aot_emit_control.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/libraries/lib-pthread/lib_pthread_wrapper.c, core/iwasm/libraries/libc-builtin/libc_builtin_wrapper.c, core/iwasm/libraries/libc-emcc/libc_emcc_wrapper.c, core/iwasm/libraries/libc-wasi/libc_wasi_wrapper.c, core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c, core/iwasm/libraries/thread-mgr/thread_manager.c, core/shared/platform/zephyr/zephyr_platform.c, core/shared/utils/bh_assert.c, core/shared/utils/bh_hashmap.c, samples/gui/wasm-runtime-wgl/src/platform/linux/iwasm_main.c, samples/workload/wasm-av1/README.md, samples/workload/wasm-av1/wasm-av1.patch, wamr-compiler/main.c
add more checks to enhance security
clear "wasi proc exit" exception before return to caller in wasm/aot call functions
fix memory profiling issue
change movdqa to movdqu in simd invokeNative asm codes to fix issue of unaligned address access
move setjmp/longjmp from libc-builtin to libc-emcc
fix zephyr platform compilation issue in latest zephyr version
=> Add more checks to enhance security (#446)

core/shared/platform/riot/platform_internal.h
RIOT removed kernel_types.h in favor of sched.h
=> Addapt to RIOT changes (#452)

core/iwasm/aot/arch/aot_reloc_aarch64.c, core/iwasm/compilation/aot_emit_numberic.c, core/iwasm/libraries/libc-emcc/libc_emcc_wrapper.c, product-mini/platforms/windows/CMakeLists.txt, wamr-compiler/CMakeLists.txt
Motivation:
we found some issues during enable the WAMR on arm devices, such as relocation issues, stack alignment issues.
Proposed change:
We optimized the relocation process for arm platform, for relocation jump table, the SP should be aligned to 16 bytes. And we also make "getentropy" worked for other non-supported platform.
=> Fix some issues for Arm platform. (#457)

core/app-framework/base/native/timer_wrapper.c, core/iwasm/libraries/lib-pthread/lib_pthread_wrapper.c, core/shared/platform/alios/alios_thread.c, core/shared/platform/common/freertos/freertos_thread.c, core/shared/platform/common/posix/posix_thread.c, core/shared/platform/include/platform_api_extension.h, core/shared/platform/include/platform_common.h, core/shared/platform/linux-sgx/sgx_thread.c, core/shared/platform/riot/riot_thread.c, core/shared/platform/windows/win_thread.c, core/shared/platform/zephyr/zephyr_thread.c, core/shared/utils/bh_queue.c, core/shared/utils/bh_queue.h, core/shared/utils/runtime_timer.c, core/shared/utils/runtime_timer.h, wamr-sdk/app/libc-builtin-sysroot/include/pthread.h
Modify the argument of os_cond_reltimedwait to uint64 type to support long time wait, and handle possible integer overflow.
=> Modify os_cond_reltimedwait to support long time wait (#461)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/compilation/aot_compiler.c, core/iwasm/compilation/aot_emit_memory.c, core/iwasm/compilation/aot_llvm_extra.cpp, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, core/iwasm/interpreter/wasm_runtime.c, samples/littlevgl/wasm-apps/src/main.c
Fix potential memory leak issue when using llvm::EngineBuilder().selectTarget()
Fix issue of accessing aot_value's fields after it is freed
Fix JIT not print failed to link import warning
Change some error messages: 'fail to' to 'failed to'
Update error message when SIMD isn't enabled
Fix install littlevgl wasm app of wasi version failed
=> Fix wamr compiler issues and refine some error messages (#470)

core/iwasm/compilation/aot_compiler.c, core/iwasm/compilation/simd/simd_floating_point.c, core/iwasm/compilation/simd/simd_floating_point.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_opcode.h
Implement SIMD f32x4/f64x2 ceil/floor/trunc/nearest opcodes
=> Implement SIMD float ceil/floor/trunc/nearest opcodes (#472)

core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot_emit_control.c, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_loader.h, core/iwasm/libraries/libc-wasi/libc_wasi_wrapper.c, doc/build_wasm_app.md, product-mini/app-samples/hello-world/build.sh, samples/basic/build.sh, samples/gui/wasm-apps/decrease/Makefile, samples/gui/wasm-apps/increase/Makefile, samples/littlevgl/wasm-apps/Makefile_wasm_app, samples/littlevgl/wasm-apps/Makefile_wasm_app_no_wasi, samples/multi-thread/wasm-apps/CMakeLists.txt, samples/simple/build.sh, test-tools/component_test/suites/01-life-cycle/test-app/build.sh, wamr-sdk/app/wamr_toolchain.cmake
Update wasm app build scripts for wasi-sdk-12.0: add --export=__main_argc_argv, remove --no-threads
Lookup function with name "__main_argc_argv" as main function besides "main"
Change module_malloc to runtime_malloc in wasi native lib
Refine classic interpreter op_block and op_br_table
Refine faster interpreter op_br_table
=> Update wasm app build scripts for wasi-sdk-12 and refine interpreter (#481)

core/iwasm/common/wasm_c_api.c
Fix incorrect func_type unpacking for results
Fix crash for multiple instance usage due to wrong size provided
Signed-off-by: Kanghua Yu <kanghua.ykh@antgroup.com>
Signed-off-by: Xiaokang Qin <xiaokang.qxk@antgroup.com>
Co-authored-by: Kanghua Yu <kanghua.ykh@antgroup.com>
=> Fix two issues for wasm-c-api (#487)

core/iwasm/aot/aot_loader.c
Modify the macro control sentences as darwin platform doesn't support mmap with MAP_32BIT flag to put the mapping address into 0-2G range.
Co-authored-by: Wenyong Huang <wenyong.huang@intel.com>
=> Fix aot bh_assert failed issue on darwin platform x86_64 target

core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/shared/mem-alloc/ems/ems_gc.h, core/shared/mem-alloc/ems/ems_kfc.c, core/shared/mem-alloc/mem_alloc.c, core/shared/mem-alloc/mem_alloc.h
Re-implement aot call_indirect opcode translation: when calling non-import function, translate it by LLVM call IR to call the function in AOTed code, so as to avoid calling runtime aot_call_indirect API which is much slower. For import function, keep calling aot_call_indirect API due to the possible pointer/string argument conversion.
And add prompt info while app heap is corrupted, change emit_leb to emit_uint32 inter fast-interp to refine footprint.
=> Refine aot call_indirect opcode translation (#492)

core/iwasm/aot/aot_loader.c, core/iwasm/interpreter/wasm_loader.c
And fix possible memory leak issue in aot loader when apply relocation failed.
=> Remove unused block_addr_cache buffer in wasm loader (#493)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_memory.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot.h, core/iwasm/compilation/aot_emit_aot_file.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/compilation/aot_emit_memory.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/compilation/simd/simd_access_lanes.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c, core/shared/utils/bh_log.h, core/shared/utils/uncommon/bh_read_file.c, samples/wasm-c-api/CMakeLists.txt, samples/workload/meshoptimizer/codecbench.patch
In some platforms, allocating memory with size 0 may return NULL but not an empty memory block, which causes runtime load, instantiate or execute wasm/aot file failed. We add checks to try to avoid allocating memory in runtime if the size is 0. And in wasm_runtime_malloc/free, output warning if allocate memory with size 0 and free memory with NULL ptr.
Also fix some coding style issues, fix handle riscv32 ilp32d issue, and fix several wasm-c-api issues.
=> Add checks to avoid wasm_runtime_malloc memory with size 0 (#507)

core/iwasm/common/wasm_native.c, core/iwasm/interpreter/wasm_runtime.c
And add native symbol node to list head when registering native symbol, so as to lookup developer's registered node firstly when linking.
=> Fix duplicated destroy shared memory's lock issue (#514)

core/shared/mem-alloc/ems/ems_alloc.c
The total size actually allocated by ealloc_hmu() might be larger than the size required to allocate, we reset the total size after allocating, so that if heap verification feature is enabled, the data to verify can be written to the right place of the suffix verification area. And in gc_realloc_vo_internal(), free the heap lock until the original data is copied to new object to return.
=> Enhance ems memory allocator (#544)

core/app-mgr/app-manager/app_manager.c, core/app-mgr/app-manager/app_manager_host.c, core/app-mgr/app-manager/module_wasm_app.c, core/app-mgr/app-manager/resource_reg.c, core/app-mgr/app-manager/watchdog.c, core/app-mgr/app-manager/watchdog.h, core/shared/mem-alloc/ems/ems_alloc.c, samples/gui/wasm-runtime-wgl/src/platform/linux/iwasm_main.c, samples/gui/wasm-runtime-wgl/src/platform/zephyr/iwasm_main.c, samples/littlevgl/vgl-wasm-runtime/src/platform/linux/iwasm_main.c, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/iwasm_main.c, samples/simple/src/iwasm_main.c, test-tools/host-tool/src/main.c, test-tools/host-tool/src/transport.c
Remove the limit of app file size no larger than 1 MB, fix possible memory leak issues when fail to install app file, change message size of aee_host_msg_callback() from uint16 type to uint32 type to fix possible integer overflow issue, and fix some coding style issues of app manager.
=> Fix app manager fail to install large app file issue (#555)

core/app-mgr/app-manager/watchdog.c, core/app-mgr/app-manager/watchdog.h, core/iwasm/compilation/aot_llvm.c, doc/build_wamr.md, product-mini/platforms/darwin/CMakeLists.txt, product-mini/platforms/linux/CMakeLists.txt, wamr-compiler/main.c
Enable SIMD by default for wamrc on x86-64 target, for iwasm on platform Linux and Darwin. And update build wamr document, fix app manager compile warning.
=> Enable SIMD by default for wamrc and iwasm (#559)

build-scripts/config_common.cmake, core/iwasm/libraries/libc-uvwasi/libc_uvwasi_wrapper.c, core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/posix.c, core/shared/platform/darwin/platform_init.c, core/shared/platform/include/platform_common.h, core/shared/platform/linux/platform_init.c, core/shared/platform/vxworks/platform_init.c, core/shared/platform/windows/platform_init.c, core/shared/platform/windows/platform_internal.h, doc/build_wamr.md
Enable to use BH_VPRINTF macro for platform Linux/Windows/Darwin/VxWorks to redirect the stdout output from platform os_printf/os_vprintf, or the wasi output from wasm app to the vprintf like callback function specified by BH_VPRINTF macro of cmake WAMR_BH_VPRINTF variable.
=> Enable to use BH_VPRINTF macro to redirect stdout output (#560)

core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/XPT2046.c, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/display.h, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/display_ili9340.c, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/display_ili9340.h, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/display_ili9340_adafruit_1480.c, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/display_indev.c, samples/workload/tensorflow/tf_lite.patch
The native function might call wasm function exported, in which the memory.grow opcode might be executed, and interpreter should update memory size after that, or load/store opcodes may run failed with "out of bounds memory access" exception thrown.
Update tensorflow sample patch, allow tensorflow wasm app to grow memory so as to run more models. And fix some compile issues of littlevgl zephyr sample for latest zephyr source code.
=> Fix interpreter not update memory size after call native func (#563)

doc/build_wamr.md, product-mini/platforms/linux/build_llvm.sh, wamr-compiler/build_llvm.py, wamr-compiler/build_llvm.sh
Upgrade it as the latest version of wasi-sdk and emsdk are based on llvm-11, align to it to use the same compiler version. And this also fixes compilation error when building wamrc with llvm-10 in Windows platform.
=> Upgrade llvm version from 10.x to 11.x for wamrc and iwasm JIT (#564)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/include/wasm_export.h, core/iwasm/interpreter/wasm_runtime.c
Remove check for heap_size==0 when creating wasi ctx, as the related data structures are allocated from global heap instead of app heap now, so it also works when app heap isn't created.
Also add v128 type for Windows so as to fix wamrc compilation error in Windows platform.
=> Remove heap size check when creating wasi ctx (#565)

assembly-script/package.json, core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c
AssemblyScript's latest compiler 0.18 exports  __new__/__pin__/unpin APIs to allocate/retain/free memory instead of __new/__retain/__release APIs in older version, we lookup functions of both version to make it compatible for both version.
=> Call asc app exported new/pin/unpin APIs to align with its latest compiler (#577)

core/shared/platform/zephyr/platform_internal.h, core/shared/platform/zephyr/zephyr_platform.c, core/shared/platform/zephyr/zephyr_thread.c, product-mini/platforms/zephyr/simple/build_and_run.sh, samples/gui/README.md, samples/littlevgl/README.md, samples/littlevgl/vgl-wasm-runtime/src/platform/zephyr/display_ili9340.c, test-tools/host-tool/src/main.c, test-tools/host-tool/src/transport.c
Fix sample littlevgl/guil build issues on zephyr platform, modify code of zephyr platform by adding some macros to control some apis to fit different zephyr version, and align to zephyr-v2.3.0 for sample littlevgl/gui as the latest zephyr version (>=v2.4.0) requires that the thread stack for the thread to create must be defined by macro but not allocating stack memory dynamically.
=> Fix sample littlevgl/gui build issues on zephyr platform (#588)

core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/ssp_config.h, core/shared/platform/android/platform_init.c, core/shared/platform/android/platform_internal.h, product-mini/platforms/android/CMakeLists.txt
Some libc APIs required by wasi native lib are missing in some Android API versions, only when the version >= 24, all APIs are supported. Add the missing APIs in android platform layer, leave them empty, report error and return failed if they are called. Also update CMakeLists.txt to enable libc wasi by default.
Co-authored-by: Wenyong Huang <wenyong.huang@intel.com>
=> Enable Android libc wasi support. (#590)

core/config.h, core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/interpreter/wasm_runtime.c, core/shared/platform/android/platform_init.c, core/shared/platform/android/platform_internal.h, core/shared/platform/common/posix/posix_thread.c, core/shared/platform/darwin/platform_init.c, core/shared/platform/darwin/platform_internal.h, core/shared/platform/linux/platform_init.c, core/shared/platform/linux/platform_internal.h, core/shared/platform/vxworks/platform_init.c, core/shared/platform/vxworks/platform_internal.h, core/shared/platform/zephyr/zephyr_time.c
1. Refine the aot call function procedure
2. fix timer integer overflow issue on zephyr platform
3. move wasm_exec_env_set_thread_info into lower layer
=> Refine aot call func procedure and fix zephyr timer overflow issue (#617)

CMakeLists.txt, core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/include/wasm_export.h, core/shared/platform/android/platform_init.c, core/shared/platform/android/platform_internal.h, core/shared/platform/common/posix/posix_thread.c, core/shared/platform/darwin/platform_init.c, core/shared/platform/darwin/platform_internal.h, core/shared/platform/linux/platform_init.c, core/shared/platform/linux/platform_internal.h, core/shared/platform/vxworks/platform_init.c, core/shared/platform/vxworks/platform_internal.h, core/shared/platform/windows/platform_internal.h, core/shared/platform/windows/win_thread.c
And fix cmake_minimum_required() deprecation warning since envoy is using cmake 3.16 or higher version.
=> Re-org thread env init/destroy for HW bound check (#631)

SECURITY.md
At a meeting last week, the Bytecode Alliance board resolved to introduce a [BA security policy](https://bytecodealliance.org/security), and apply it to some core projects to begin with, including WAMR.
=> Refer to BA security policy (#635)

core/iwasm/common/wasm_application.c, core/iwasm/include/wasm_export.h, samples/spawn-thread/src/main.c, samples/wasm-c-api/CMakeLists.txt, samples/wasm-c-api/src/callback.c, samples/wasm-c-api/src/callback_chain.c, samples/wasm-c-api/src/callback_chain.wat, samples/wasm-c-api/src/global.c, samples/wasm-c-api/src/globalexportimport-0.wat, samples/wasm-c-api/src/globalexportimport-1.wat, samples/wasm-c-api/src/globalexportimport.c, samples/wasm-c-api/src/hello.c, samples/wasm-c-api/src/multi.c, samples/wasm-c-api/src/reflect.c, samples/wasm-c-api/src/trap.c
And enable to copy back the return value of wasm main function when calling wasm_application_execute_main, add license headers in wasm-c-api samples, fix several issues reported by klocwork.
=> Add wasm-c-api nested function calls sample (#652)

product-mini/platforms/linux-sgx/enclave-sample/App/App.cpp
fix the warnings as below:
App/App.cpp: In function ‘int wamr_pal_init(const wamr_pal_attr*)’:
App/App.cpp:759:1: warning: control reaches end of non-void function [-Wreturn-type]
759 | }
| ^
In file included from /usr/include/string.h:495,
from App/App.cpp:9:
In function ‘char* strncpy(char*, const char*, size_t)’,
inlined from ‘int enclave_init(sgx_enclave_id_t*)’ at App/App.cpp:104:16:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: ‘char* __builtin___strncpy_chk(char*, const char*, long unsigned int, long unsigned int)’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
|          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
=> sgx: fix the build warning (#653)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_runtime_common.h, core/iwasm/include/wasm_export.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_runtime.c, product-mini/platforms/linux-sgx/enclave-sample/App/App.cpp, product-mini/platforms/linux-sgx/enclave-sample/Enclave/Enclave.cpp
Add new API wasm_runtime_set_wasi_args_ex to support populate stdio fds
Signed-off-by: LiFeng <lifeng68@huawei.com>
=> IO: support populate fds into WASM application (#655)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_runtime_common.h, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, samples/wasm-c-api/CMakeLists.txt, samples/wasm-c-api/src/callback_chain.c, samples/wasm-c-api/src/hello.c
And update loader error messages for latest spec cases, fix aot compiler build error based on latest LLVM code base.
=> Enable call wasm-c-api native func directly from interpreter (#656)

core/iwasm/common/wasm_c_api.c, core/iwasm/include/wasm_c_api.h, core/iwasm/include/wasm_export.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_runtime.c, product-mini/platforms/linux/CMakeLists.txt
And add wasm_engine_new_with_args() declaration in wasm_c_api.h
Fix wasm-c-api frame func_offset issue in fast interp mode
Remove sanitize compiler flag in product-mini linux CMakeLists.txt
=> Implement wasm-c-api wasm_config related APIs (#665)

.github/workflows/android.yml, .github/workflows/linux.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, README.md, TSC_Charter.md, core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_c_api_internal.h, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_runtime_common.h, core/iwasm/compilation/aot_emit_table.c, core/iwasm/include/wasm_c_api.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h, doc/wasm_c_api.md, samples/wasm-c-api/CMakeLists.txt, samples/wasm-c-api/src/hostref.c, samples/wasm-c-api/src/hostref.wat, samples/wasm-c-api/src/memory.c, samples/wasm-c-api/src/memory.wat, samples/wasm-c-api/src/table.c, samples/wasm-c-api/src/table.wat
Remove unnecessary functions and implement more APIs:
- wasm_##name##same
- wasm##name##as_ref
- wasm_ref_as##name##
- wasm_ref_delete
- wasm_module_validate
- wasm_table_get/set/size
- wasm_memory_size
- wasm_config_new
- wasm_foreign_new
And add more wasm-c-api samples, update the related documen, add more CI rules.
=> Implement most missing wasm-c-api APIs (#303) (#676)

core/iwasm/aot/arch/aot_reloc_aarch64.c, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_c_api_internal.h, core/iwasm/compilation/aot.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, core/shared/mem-alloc/ems/ems_gc_internal.h, product-mini/platforms/darwin/main.c, product-mini/platforms/linux/CMakeLists.txt, product-mini/platforms/linux/main.c, product-mini/platforms/nuttx/main.c, product-mini/platforms/vxworks/main.c
And refine some coding styles, fix JIT compiler data wasm table create issue, add license header for some files.
=> Fix issues reported by gcc -fsanitize flag (#678)

core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot_compiler.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_runtime.c, core/shared/platform/include/platform_api_extension.h, core/shared/platform/windows/win_thread.c, product-mini/platforms/alios-things/aos.mk
Implement wasm_runtime_init_thread_env() for Windows platform by calling os_thread_env_init(): if current thread is created by developer himself but not runtime, developer should call wasm_runtime_init_thread_env() to init the thread environment before calling wasm function, and call wasm_runtime_destroy_thread_env() before thread exits.
And clear compile warnings for Windows platform, fix compile error for AliOS-Things platform
=> Implement wasm_runtime_init_thread_env for Windows platform (#683)

core/iwasm/common/arch/invokeNative_arm_vfp.s, core/iwasm/common/arch/invokeNative_thumb.s, core/iwasm/common/arch/invokeNative_thumb_vfp.s
Make sp 8 byte aligned in invokeNative assembly on ARM.
=> Make sp 8 byte aligned in invokeNative on ARM (#697)

core/iwasm/common/wasm_runtime_common.h
Some of the function arguments were named as "export" in core/iwasm/common/wasm_runtime_common.h, which result in conflicts with the C++11 keyword. Change them to other to fix the compilation error.
=> Change arg name 'export' to other to fix keyword conflict in C++11 (#745)

.clang-format, .clang-tidy, ci/run_pre_commit_check.py
Customize clang-format coding styles for C source files based on Mozilla template.
To check whether the C source codes are well formatted:
``` bash
$ cd ${wamr-root}
$ clang-format --Werror --dry-run --style=file path/to/file
```
To format the C source codes in place
``` bash
$ cd ${wamr_root}
$ clang-format -i --style=file path/to/file
```
=> Customize clang-format coding styles based on Mozilla template (#770)

core/iwasm/aot/aot_loader.c, core/iwasm/compilation/aot_emit_aot_file.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c
Currently the string in the wasm/aot file will be duplicated and stored
into const string list/set in interpreter/aot loader, which leads to extra
unnecessary memory consumption if the file buffer can be referred to
after loading. We refine the string storage by:
- if the file buffer can be referred to after loading and it is writable, we
reuse the file buffer to store the string but not store it into the const
string set: move string backward and append '\0'
- emit string with '\0' only for XIP mode in which the AOT file is readonly
- if the file buffer cannot be referred to, e.g. in app manager, keep the
same behavior as before
=> Refine interp/aot string storage and emitting (#820)

.github/workflows/compilation_on_sgx.yml, .github/workflows/spec_test.yml, tests/wamr-test-suites/spec-test-script/all.py, tests/wamr-test-suites/spec-test-script/runtest.py, tests/wamr-test-suites/test_wamr.sh
Port spec-test-script/all.sh to spec-test-script/all.py and enable to run
spec cases with multiple threads parallelly:
- It reduces spec_test.yml from ~14min to ~9min and reduces
compilation_on_sgx.yml from ~18min to ~12min
- run `./test_wamr.sh` will keep the same experience likes before by default
- run `./test_wamr.sh -P` will enable parallelism mode
- in parallelism mode, all.py will be in a less-output mode. It only outputs
the last words of failed cases and will not output logs for those passed
=> Speed up the spec case test by parallelism (#819)

core/iwasm/aot/arch/aot_reloc_x86_64.c
Fix pointer overflow of `(uint8 *)symbol_addr + reloc_addend` detected by UBSan:
```
core/iwasm/aot/arch/aot_reloc_x86_64.c:232:43: runtime error: addition of unsigned offset to 0x000041209004 overflowed to 0x000041209000
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior core/iwasm/aot/arch/aot_reloc_x86_64.c:232:43
```
=> aot_reloc_x86_64: Fix pointer overflows (#809)

core/iwasm/aot/aot_reloc.h, core/iwasm/compilation/aot_compiler.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/compilation/aot_llvm_extra.cpp, core/iwasm/include/aot_export.h, tests/wamr-test-suites/spec-test-script/runtest.py, wamr-compiler/main.c
Enable LLVM link time optimization for AOT and enable it by default,
and provide "wamrc --disable-llvm-lto" option to disable it.
And modify the spec test script, disable it by default when testing
spec cases.
=> Enable LLVM link time optimization (LTO) for AOT (#831)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_reloc.h, core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/aot/arch/aot_reloc_aarch64.c, core/iwasm/aot/arch/aot_reloc_arc.c, core/iwasm/aot/arch/aot_reloc_arm.c, core/iwasm/aot/arch/aot_reloc_mips.c, core/iwasm/aot/arch/aot_reloc_riscv.c, core/iwasm/aot/arch/aot_reloc_thumb.c, core/iwasm/aot/arch/aot_reloc_x86_32.c, core/iwasm/aot/arch/aot_reloc_x86_64.c, core/iwasm/aot/arch/aot_reloc_xtensa.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot_emit_aot_file.c, core/iwasm/compilation/aot_emit_control.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/interpreter/wasm_runtime.c, core/shared/mem-alloc/ems/ems_alloc.c, core/shared/mem-alloc/ems/ems_kfc.c, wamr-compiler/CMakeLists.txt
Fix some potential pointer overflows in aot applying relocations and
several other places.
And add sanitizer compiler flags to wamrc CMakeLists.txt to detect
such issues.
=> Fix potential pointer overflows (#826)

core/iwasm/common/gc/gc_type.c, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h
Implement loading ref type of global and table
Add macro controls of ENABLE_GC/ENABLE_REF_TYPES to explicitly distinguish
the code piece's belonging, to GC, to REF_TYPEs for to both.
Change ref_type field of ArrayType to pointer to save memory.
Fix bug of is_subtype_of check of ref types.
=> Implement loading ref type of global/table and fix some issues (#840)

core/iwasm/aot/aot_loader.c, core/iwasm/compilation/aot_emit_aot_file.c
Emit the correct binary type and machine type in AOT file
for win64/win32 system, and handle them in aot loader.
=> Fix win32 aot endian and machine type check errors (#855)

core/iwasm/aot/arch/aot_reloc_aarch64.c
Treat R_AARCH64_JUMP26 same as R_AARCH64_CALL26, both of their
relocation operation is S + A - P, the difference is that one is for call
(BL) instructions, the other is for jump (B) instructions.
=> Implement relocation R_AARCH64_JUMP26 for aarch64 (#873)

core/iwasm/aot/aot_loader.c, core/iwasm/compilation/aot_compiler.c, core/shared/platform/windows/platform_internal.h, core/shared/platform/windows/win_thread.c
And fix compilation error of when build wamrc, fix compilation warnings
=> Implement GetCurrentThreadStackLimits() for Windows 7 (#914)

core/iwasm/compilation/aot_llvm.c, core/shared/platform/common/posix/posix_memmap.c, product-mini/platforms/darwin/CMakeLists.txt, tests/wamr-test-suites/spec-test-script/all.py, tests/wamr-test-suites/spec-test-script/runtest.py, wamr-compiler/main.c
Fix some issues on MacOS platform
- Enable libc-wasi by default
- Set target abi to "gnu" if it is not set for wamrc to avoid generating
object file of unsupported Mach-O format
- Set `<vendor>-<sys>` info according to target abi for wamrc to support
generating AOT file for other OSs but not current host
- Set cpu name if arch/abi/cpu are not set to avoid checking SIMD
capability failed
- Set size level to 1 for MacOS/Windows platform to avoid relocation type
unsupported warning
- Clear posix_memmap.c compiling warning
- Fix spec case test script issues, enable test spec cases on MacOS
=> Fix some issues on MacOS platform (#937)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, product-mini/platforms/windows/main.c, wamr-compiler/main.c
Enable running XIP file on Windows platform.
And add more strict checks for wamrc to report error when the input file
is same with output file, or the input file is AOT file but not wasm file.
=> Enable Windows XIP (#944)

core/iwasm/aot/aot_loader.c, core/iwasm/common/wasm_runtime_common.c, core/iwasm/interpreter/wasm_loader.c, product-mini/platforms/linux-sgx/enclave-sample/Enclave/Enclave.cpp
Refine is_xip_file check, when e_type isn't E_TYPE_XIP, just return false
and no need to go through all the other sections of the AOT file.
Refine pointer range check, convert pointer to uintptr_t type before
comparison to yield possible sanitizer pointer overflow error.
=> Refine is_xip_file and pointer range check (#965)

samples/workload/XNNPACK/CMakeLists.txt
XNNPACK code base is updating quickly, we specify a commit ID
for it so as to build XNNPACK workload successfully.
=> Specify a commit ID for XNNPACK workload (#966)

core/config.h, core/iwasm/common/gc/gc_object.c, core/iwasm/common/gc/gc_object.h, core/iwasm/common/gc/gc_type.c, core/iwasm/common/gc/gc_type.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_opcode.h, tests/wamr-test-suites/spec-test-script/all.py, tests/wamr-test-suites/spec-test-script/gc_ignore_cases.patch, tests/wamr-test-suites/spec-test-script/runtest.py, tests/wamr-test-suites/spec-test-script/thread_proposal_ignore_cases.patch, tests/wamr-test-suites/test_wamr.sh
Implement GC bytecode validation in loader stage, except for opcode
let and and func.bind. Pass the related spec cases.
And implement some GC object related APIs.
The source code may be not so elegant, we will optimize it in the future.
=> Implement GC bytecode validation (#918)

core/iwasm/common/gc/gc_object.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, tests/wamr-test-suites/spec-test-script/all.py, tests/wamr-test-suites/spec-test-script/gc_ignore_cases.patch, tests/wamr-test-suites/spec-test-script/runtest.py, tests/wamr-test-suites/test_wamr.sh
Implement stack frame GC object tracking for the reclaim root set traversing
And update wamr-test-suites for latest spec cases:
- Update GC spec cases to latest version
- Patch spec interpreter to support building it with ocaml 4.0.8
- Fix runtest.py to ref.null result
- Comment some supported cases in type-cannon and type-equivalence
=> Implement stack frame GC object tracking (#1065)

core/iwasm/fast-jit/cg/x86-64/jit_codegen_x86_64.cpp
Directly patch the offset in condition jmp instructions as
the offset generated by asmjit is always 0.
=> Fix fast-jit codegen lower_select issue (#1082)

core/iwasm/aot/aot_loader.c
Fix issues in PR "Refine interp/aot string storage and emitting (#820)",
which had a few issues:
- It looks a wrong byte to mark the flag
- It doesn't work for long strings (>= 0x80 in case of little endian)
This commit fixes them by maintaining a list of loaded symbols while loading
relocation section to avoid reading a string repeatedly, and no need to mark
the flag again.
=> aot_loader.c: Fix issues in "Refine interp/aot string storage" (#1102)

core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c
Fix an UBSan complaint introduced by recent change by adding more checks
to word_copy:
```
wasm_interp_fast.c:792:9: runtime error: applying zero offset to null pointer
```
=> interpreter: Fix an UBSan complaint in word_copy (#1106)

samples/ref-types/src/hello.c
Fix ref-types sample running error due to using invalid externref signatures
=> Fix ref-types sample invalid externref signature (#1119)

core/iwasm/common/wasm_application.c, core/iwasm/common/wasm_exec_env.h, core/iwasm/libraries/thread-mgr/thread_manager.c, core/iwasm/libraries/thread-mgr/thread_manager.h
Fix wasm_application_execute_main/wasm_application_execute_func not waiting for
other threads to terminate in multi-thread mode, which causes that the exception
thrown by other threads may haven't been spreaded to current main thread, and
cannot be detected by the caller, as reported in #1131.
=> Fix execute_main not wait for other threads (#1137)

core/iwasm/compilation/aot_llvm_extra.cpp, core/iwasm/libraries/thread-mgr/thread_manager.c
Fix aot compiler compilation errors when the llvm version is 14.0,
and clear one compilation warning of thread_manager.c.
=> Fix wamrc build error with llvm-14 (#1140)

core/iwasm/interpreter/wasm_runtime.c
Fix allocate zero size memory warning reported by wasm_runtime_malloc
when allocating the import fun pointers if the import func count is 0:
`warning: wasm_runtime_malloc with size zero`
=> Fix allocate zero size memory warning (#1143)

core/shared/platform/common/posix/posix_thread.c
Add return value check for os_thread_get_stack_boundary before touch_pages
in the initialization of memory access bound check with hardware trap.
=> Add check for stack_min_addr in bound check with hardware trap (#1166)

core/iwasm/fast-jit/cg/x86-64/jit_codegen_x86_64.cpp, core/iwasm/fast-jit/fe/jit_emit_compare.c, core/iwasm/fast-jit/fe/jit_emit_control.c, core/iwasm/fast-jit/fe/jit_emit_conversion.c, core/iwasm/fast-jit/fe/jit_emit_function.c, core/iwasm/fast-jit/fe/jit_emit_function.h, core/iwasm/fast-jit/fe/jit_emit_memory.c, core/iwasm/fast-jit/fe/jit_emit_numberic.c
And remove clear_values for opcode br_if as the jit registers
can be used in the same basic block.
=> Refactor emitting callnative/callbc IRs (#1206)

core/config.h, core/iwasm/fast-jit/cg/x86-64/jit_codegen_x86_64.cpp, core/iwasm/fast-jit/fe/jit_emit_compare.c, core/iwasm/fast-jit/fe/jit_emit_conversion.c, core/iwasm/fast-jit/fe/jit_emit_variable.c, core/iwasm/fast-jit/jit_dump.c, core/iwasm/fast-jit/jit_frontend.c, core/iwasm/interpreter/wasm_interp.h, core/iwasm/interpreter/wasm_runtime.c
Move jit spill cache to the end of interp frame to reduce footprint
Fix codegen compare float issue: should not overwritten the source registers
Fix float to int conversion check integer overflow issue
Unify the float compare
Fix get_global issue
=> Fix fast jit issues (#1208)

core/iwasm/compilation/aot_compiler.c
Disable LoopUnswitch pass for LLVM 15 - C binding has been removed and binding
for new pass hasn't been added. Need to reenable when binding gets added to
LLVM or when we implement it in WAMR.
=> Temporarily disable LoopUnswitch pass (#1183)

build-scripts/build_llvm.py, core/iwasm/compilation/aot_emit_const.c, core/iwasm/compilation/aot_emit_control.c, core/iwasm/compilation/aot_emit_exception.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/compilation/aot_emit_memory.c, core/iwasm/compilation/aot_emit_table.c, core/iwasm/compilation/aot_emit_variable.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/compilation/aot_llvm_extra.cpp, core/iwasm/compilation/simd/simd_load_store.c
Enable opaque pointer for aot compiler to meet the requirements
of LLVM 14 and 15, change calling of LLVMBuildLoad/LLVMBuildCall/LLVMInBoundsGEP
to calling of LLVMBuildLoad2/LLVMBuildCall2/LLVMInBoundsGEP2, and pass
the related type.
And update the build script to build LLVM 14.x by default.
=> Enable opaque pointer for aot compiler to fit LLVM 14/15 (#1218)

core/iwasm/fast-jit/cg/x86-64/jit_codegen_x86_64.cpp
If the branches of lookupswitch is relatively big, lookup the dst
label address to jump from the address table but not compare
the value of branch one by one.
=> Refine fast jit backend translation of IR lookupswitch (#1264)

core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_runtime_common.h, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h
Implement boundary check with hardware trap for interpreter on
64-bit platforms:
- To improve the performance of interpreter and Fast JIT
- To prepare for multi-tier compilation for the feature
Linux/MacOS/Windows 64-bit are enabled.
=> Implement interpreter hw bound check (#1309)

core/iwasm/compilation/simd/simd_conversions.c
Change "==" to "=" when setting trunc_type[] array elements.
=> Fix typo in simd_conversions.c (#1428)

core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/common/wasm_c_api.c, core/iwasm/common/wasm_runtime_common.c
Make AOT module instance's tables member same as interpreter module instance's, so as to unify this field and prepare for the API unifying.
=> Unify AOT/interp module inst's tables member (#1503)

core/iwasm/libraries/lib-socket/src/wasi/wasi_socket_ext.c
While compiling the file wasi_socket_ext.c with pedantic options (typically `-Wimplicit-int-conversion` and `-Wmissing-prototypes`), some warnings are raised.
This PR addresses those warnings by adding missing static statements before functions and explicitly casting a narrowing conversion.
And fix the error handling after calling getpeername.
=> socket: Explicit narrowing type cast and add missing static keywords (#1539)

.github/workflows/compilation_on_android_ubuntu.yml, core/iwasm/aot/aot_loader.c, core/iwasm/compilation/aot_compiler.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/compilation/aot_llvm.c, core/iwasm/compilation/aot_llvm.h, core/iwasm/compilation/aot_llvm_extra.cpp, core/iwasm/compilation/iwasm_compl.cmake, core/iwasm/compilation/orc_extra/aot_orc_extra.cpp, core/iwasm/compilation/orc_extra/aot_orc_extra.h, tests/wamr-test-suites/test_wamr.sh
Use LLJIT to do eager compilation
Use LLLazyJIT to do lazy compilation
=> Upgrade to ORCv2 APIs (#1456)

core/iwasm/common/wasm_runtime_common.c
Change `wasi-sdk-16.0` to `wasi-sdk-12.0` in wasm_runtime_show_app_heap_corrupted_prompt, which was mis-modified by previous commit.
=> Restore the app heap corrupted prompt (#1885)

core/iwasm/common/wasm_runtime_common.c, core/iwasm/compilation/aot_emit_function.c, core/iwasm/compilation/aot_emit_memory.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/libraries/thread-mgr/thread_manager.c, samples/wasi-threads/README.md, samples/wasi-threads/wasm-apps/thread_termination.c
Raising "wasi proc exit" exception, spreading it to other threads and then clearing it in all threads may result in unexpected behavior: the sub thread may end first, handle the "wasi proc exit" exception and clear exceptions of other threads, including the main thread. And when main thread's exception is cleared, it may continue to run and throw "unreachable" exception. This also leads to some assertion failed.
Ignore exception spreading for "wasi proc exit" and don't clear exception of other threads to resolve the issue.
And add suspend flag check after atomic wait since the atomic wait may be notified by other thread when exception occurs.
=> thread-mgr: Fix spread "wasi proc exit" exception and atomic.wait issues (#1988)

core/iwasm/common/wasm_memory.c, core/iwasm/common/wasm_memory.h, core/iwasm/common/wasm_runtime_common.c, core/iwasm/common/wasm_shared_memory.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h, core/iwasm/libraries/thread-mgr/thread_manager.c
Attempt to fix data races when using threads.
- Protect access (from multiple threads) to exception and memory
- Fix shared memory lock usage
=> Add/reorganize locks for thread synchronization (#1995)

core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c
Load memory data size in each time memory access boundary check in
multi-threading mode since it may be changed by other threads when
memory growing.
And use `memory->memory_data_size` instead of
`memory->num_bytes_per_page * memory->cur_page_count` to refine
the code.
=> Fix interpreter read linear memory size for multi-threading (#2088)

.github/workflows/build_wamr_vscode_ext.yml, RELEASE_NOTES.md, core/version.h, test-tools/wamr-ide/VSCode-Extension/package.json
And restore the CI vsce publish and change the wamride publisher name.
=> Update version number and release notes (#2103)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/aot/arch/aot_reloc_x86_64.c, core/iwasm/compilation/aot_llvm_extra.cpp, product-mini/platforms/posix/main.c, tests/benchmarks/README.md, tests/benchmarks/coremark/README.md, tests/benchmarks/coremark/test_pgo.sh, tests/benchmarks/jetstream/README.md, tests/benchmarks/jetstream/test_pgo.sh, tests/benchmarks/sightglass/README.md, tests/benchmarks/sightglass/test_pgo.sh
- Uncomment PGO for indirect calls and implement the relocation type R_X86_64_GOTPCREL
- Fix issues of flags in raw profile version
- Add LICM pass for wamrc when pgo is enabled
- Add test pgo scripts for benchmark coremark/sightglass/polybench
=> Fix issues of AOT static PGO, add test pgo scritps for benchmarks (#2225)

core/iwasm/compilation/aot_llvm_extra.cpp
Explicitly disable static counter allocation for value profiler since it will be allocated by runtime.
=> Disable static counter allocation for value profiler (#2241)

.github/workflows/nightly_run.yml
Adds more automated way for errors like this:
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/5328561662
Proposed dependency : https://github.com/nick-fields/retry
=> Add retries to flaky step in nightly run CI (#2306)

core/shared/platform/android/platform_internal.h
The CI might use clang-17 to build iwasm for Android platform and it may report compilation error:
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/6308980430/job/17128073777
/home/runner/work/wasm-micro-runtime/wasm-micro-runtime/core/iwasm/libraries/libc-wasi/sandboxed-system-primitives/src/blocking_op.c:45:19: error: call to undeclared function 'preadv'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
ssize_t ret = preadv(fd, iov, iovcnt, offset);
^
Explicitly declare preadv and pwritev in android platform header file to resolve it.
=> Fix compilation error on Android platform (#2594)

.github/workflows/coding_guidelines.yml, core/iwasm/aot/aot_runtime.c, core/iwasm/common/wasm_application.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_interp_fast.c, core/iwasm/interpreter/wasm_runtime.c, product-mini/platforms/posix/main.c, product-mini/platforms/windows/main.c
Avoid the stack traces getting mixed up together when multi-threading is enabled by using exception_lock/unlock in dumping the call stacks.
And remove duplicated call stack dump in wasm_application.c.
Also update coding guideline CI to fix the clang-format-12 not found issue.
=> Improve stack trace dump and fix coding guideline CI (#2599)

core/iwasm/compilation/aot.c, core/iwasm/compilation/aot.h, core/iwasm/compilation/aot_emit_gc.c, core/iwasm/include/aot_export.h, core/iwasm/interpreter/wasm.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, wamr-compiler/main.c
The struct field size and field offset of a wasm struct may vary
in 32-bit target and 64-bit target, the aot compiler should not
use the offset calculated in wasm loader. It re-calculates them
according to the target info and whether GC is enabled.
And set the alignment of sruct.get/set when field size is 2, 4, or 8.
=> Fix GC struct field offset calculation in AOT compiler (#2746)

core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c
The issue was reported in #3090.
=> fast-interp: Fix stack recovery for else branch (#3100)

RELEASE_NOTES.md, core/iwasm/compilation/aot_compiler.c, core/iwasm/fast-jit/jit_frontend.c, core/iwasm/interpreter/wasm_interp_classic.c, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_mini_loader.c, wamr-compiler/main.c
The format of sub opcodes after misc, simd and atomic prefix is leb u32.
The issue was found in #2921.
=> Fix read and validation of misc/simd/atomic sub opcodes (#3115)

core/shared/platform/zephyr/zephyr_thread.c
For use with WAMR_BUILD_LIB_PTHREAD, add os_thread_detach, os_thread_exit, os_cond_broadcast.
=> zephyr: Add missing pthread library functions (#3291)

test-tools/wamr-ide/VSCode-Extension/tsconfig.json
Set `moduleResolution` as `node16` in tsconfig.json.
ps.
https://github.com/bytecodealliance/wasm-micro-runtime/actions/runs/9296272681/job/25586420457
```
node_modules/@vscode/test-electron/out/util.d.ts(1,23): error TS1452:
'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.
```
=> Fix test-wamr-ide CI failure (#3485)

core/iwasm/aot/aot_loader.c, core/iwasm/aot/aot_runtime.c, core/iwasm/aot/aot_runtime.h, core/iwasm/common/wasm_runtime_common.c, core/iwasm/include/wasm_c_api.h, core/iwasm/include/wasm_export.h, core/iwasm/interpreter/wasm_loader.c, core/iwasm/interpreter/wasm_runtime.c, core/iwasm/interpreter/wasm_runtime.h
Add no_resolve to LoadArgs and wasm_runtime_resolve_symbols so one can delay resolving of symbols.
This is useful for inspecting the module between loading and instantiating.
=> Add no_resolve to LoadArgs and wasm_runtime_resolve_symbols (#3790)
